const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const { DatabaseSync } = require('node:sqlite');

const ROOT = __dirname;
const DATA = path.join(ROOT, 'data');
fs.mkdirSync(path.join(DATA, 'uploads'), { recursive: true });
const db = new DatabaseSync(path.join(DATA, 'hercare.sqlite'));
db.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY, name TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('patient','doctor','lab')), email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS sessions(token_hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), expires_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS patients(id TEXT PRIMARY KEY, user_id TEXT UNIQUE REFERENCES users(id), full_name TEXT NOT NULL, health_id TEXT UNIQUE NOT NULL, blood_group TEXT, pregnancy_week INTEGER, due_date TEXT, language TEXT DEFAULT 'en', region TEXT DEFAULT 'North Indian');
CREATE TABLE IF NOT EXISTS consents(id INTEGER PRIMARY KEY, patient_id TEXT NOT NULL REFERENCES patients(id), grantee TEXT NOT NULL, scope TEXT NOT NULL, enabled INTEGER NOT NULL DEFAULT 0, updated_at TEXT NOT NULL, UNIQUE(patient_id,grantee,scope));
CREATE TABLE IF NOT EXISTS pain_checkins(id INTEGER PRIMARY KEY AUTOINCREMENT, patient_id TEXT NOT NULL REFERENCES patients(id), score INTEGER NOT NULL CHECK(score BETWEEN 0 AND 10), symptoms TEXT NOT NULL DEFAULT '[]', note TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS alerts(id TEXT PRIMARY KEY, patient_id TEXT NOT NULL REFERENCES patients(id), kind TEXT NOT NULL, status TEXT NOT NULL, details TEXT NOT NULL, location_shared INTEGER NOT NULL, created_at TEXT NOT NULL, safe_at TEXT);
CREATE TABLE IF NOT EXISTS test_orders(id TEXT PRIMARY KEY, patient_id TEXT NOT NULL REFERENCES patients(id), lab_user_id TEXT NOT NULL REFERENCES users(id), test_name TEXT NOT NULL, status TEXT NOT NULL, ordered_by TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS reports(id TEXT PRIMARY KEY, order_id TEXT NOT NULL REFERENCES test_orders(id), patient_id TEXT NOT NULL REFERENCES patients(id), file_name TEXT NOT NULL, stored_name TEXT NOT NULL, summary TEXT NOT NULL DEFAULT '', uploaded_by TEXT NOT NULL REFERENCES users(id), created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS visits(id TEXT PRIMARY KEY, patient_id TEXT NOT NULL REFERENCES patients(id), clinician TEXT NOT NULL, visit_type TEXT NOT NULL, visit_at TEXT NOT NULL, note TEXT NOT NULL DEFAULT '', follow_up TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS medicines(id TEXT PRIMARY KEY, patient_id TEXT NOT NULL REFERENCES patients(id), name TEXT NOT NULL, directions TEXT NOT NULL, reminder_time TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS medicine_logs(id INTEGER PRIMARY KEY AUTOINCREMENT, medicine_id TEXT NOT NULL REFERENCES medicines(id), patient_id TEXT NOT NULL REFERENCES patients(id), taken_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS access_log(id INTEGER PRIMARY KEY AUTOINCREMENT, patient_id TEXT NOT NULL REFERENCES patients(id), actor_id TEXT NOT NULL REFERENCES users(id), action TEXT NOT NULL, resource TEXT NOT NULL, created_at TEXT NOT NULL);`);
const now = () => new Date().toISOString();
const hash = s => crypto.createHash('sha256').update(s).digest('hex');
const passwordHash = (password, salt) => crypto.scryptSync(password, salt, 64).toString('hex');
function seedUser(id, name, role, email, password) {
  const salt = `hercare-demo-${id}`;
  db.prepare('INSERT OR IGNORE INTO users(id,name,role,email,password_hash) VALUES(?,?,?,?,?)').run(id,name,role,email,`${salt}:${passwordHash(password,salt)}`);
}
seedUser('patient-anaya','Anaya Mehta','patient','anaya@hercare.demo','Care2026!');
seedUser('doctor-meera','Dr. Meera Shah','doctor','meera@hercare.demo','Care2026!');
seedUser('lab-city','City Diagnostics Lab','lab','lab@hercare.demo','Care2026!');
db.prepare(`INSERT OR IGNORE INTO patients(id,user_id,full_name,health_id,blood_group,pregnancy_week,due_date) VALUES('p-anaya','patient-anaya','Anaya Mehta','HC-2847-1936','O+',28,'2026-12-17')`).run();
db.prepare(`INSERT OR IGNORE INTO test_orders(id,patient_id,lab_user_id,test_name,status,ordered_by,created_at) VALUES('LAB-10284','p-anaya','lab-city','Glucose screening','awaiting_report','doctor-meera',?)`).run(now());
db.prepare(`INSERT OR IGNORE INTO visits(id,patient_id,clinician,visit_type,visit_at,note,follow_up,created_at) VALUES('visit-1','p-anaya','Dr. Meera Shah','Antenatal consultation','2026-09-30T10:30:00+05:30','Routine review; patient questions discussed.','Continue supplements; bring glucose report.',?)`).run(now());
for (const [id,name,directions,time] of [['med-iron','Iron + folic acid','1 tablet after breakfast','08:00'],['med-d','Vitamin D','1 tablet after lunch','13:00']]) db.prepare('INSERT OR IGNORE INTO medicines(id,patient_id,name,directions,reminder_time) VALUES(?,?,?,?,?)').run(id,'p-anaya',name,directions,time);
for (const [grantee,scope,enabled] of [['husband','emergency_alert',1],['mother','emergency_alert',1],['father','emergency_alert',1],['doctor','emergency_alert',0],['family','full_record',0],['contacts','emergency_location',1],['doctor','health_record',1]]) db.prepare('INSERT OR IGNORE INTO consents(patient_id,grantee,scope,enabled,updated_at) VALUES(?,?,?,?,?)').run('p-anaya',grantee,scope,enabled,now());
const starter = [[2,[]],[4,[]],[6,[]],[1,[]],[2,[]],[8,[]],[4,[]],[6,[]],[3,[]],[1,[]]];
if (!db.prepare('SELECT 1 FROM pain_checkins WHERE patient_id=?').get('p-anaya')) for (let i=0;i<starter.length;i++) db.prepare('INSERT INTO pain_checkins(patient_id,score,symptoms,note,created_at) VALUES(?,?,?,?,?)').run('p-anaya',starter[i][0],'[]','',new Date(Date.now()-(starter.length-i)*60000).toISOString());

const mime = {'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.webmanifest':'application/manifest+json; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.pdf':'application/pdf'};
function send(res,status,payload,headers={}) { res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers});res.end(JSON.stringify(payload)); }
function fail(res,status,message){send(res,status,{error:message});}
function readBody(req,max=8*1024*1024){return new Promise((resolve,reject)=>{let n=0,b=[];req.on('data',c=>{n+=c.length;if(n>max){reject(Object.assign(new Error('Request too large'),{status:413}));req.destroy();}else b.push(c)});req.on('end',()=>{try{resolve(JSON.parse(Buffer.concat(b).toString()||'{}'))}catch{reject(Object.assign(new Error('Invalid JSON body'),{status:400}))}});req.on('error',reject)})}
function auth(req){const token=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('hc_session='))?.slice(11);if(!token)return null;const s=db.prepare('SELECT u.id,u.name,u.role,u.email FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>? AND u.active=1').get(hash(token),now());return s||null}
function requireRole(user,...roles){return Boolean(user&&roles.includes(user.role))}
function patientFor(user){return user.role==='patient'?db.prepare('SELECT * FROM patients WHERE user_id=?').get(user.id):db.prepare('SELECT * FROM patients WHERE id=?').get('p-anaya')}
function audit(patient,user,action,resource){db.prepare('INSERT INTO access_log(patient_id,actor_id,action,resource,created_at) VALUES(?,?,?,?,?)').run(patient.id,user.id,action,resource,now())}
function checkPassword(user,password){const [salt,stored]=user.password_hash.split(':');return crypto.timingSafeEqual(Buffer.from(passwordHash(password,salt),'hex'),Buffer.from(stored,'hex'))}
async function api(req,res,url){
  if(req.method==='POST'&&url.pathname==='/api/auth/register'){const b=await readBody(req);const name=String(b.name||'').trim().slice(0,120),email=String(b.email||'').trim().toLowerCase(),password=String(b.password||'');if(name.length<2||!email.includes('@')||password.length<10)return fail(res,400,'Enter a name, valid email, and password of at least 10 characters');const id=crypto.randomUUID(),salt=crypto.randomBytes(16).toString('hex'),healthId='HC-'+crypto.randomBytes(5).toString('hex').toUpperCase();try{db.prepare('INSERT INTO users(id,name,role,email,password_hash) VALUES(?,?,?,?,?)').run(id,name,'patient',email,salt+':'+passwordHash(password,salt));db.prepare('INSERT INTO patients(id,user_id,full_name,health_id,language,region) VALUES(?,?,?,?,?,?)').run('p-'+id,id,name,healthId,String(b.language||'en').slice(0,10),String(b.region||'').slice(0,80));const token=crypto.randomBytes(32).toString('base64url');db.prepare('INSERT INTO sessions(token_hash,user_id,expires_at) VALUES(?,?,?)').run(hash(token),id,new Date(Date.now()+43200000).toISOString());send(res,201,{user:{id,name,role:'patient'},healthId},{'set-cookie':'hc_session='+token+'; HttpOnly; SameSite=Lax; Path=/; Max-Age=43200'})}catch(e){if(String(e.message).includes('UNIQUE'))return fail(res,409,'An account already uses that email');throw e}return}if(req.method==='POST'&&url.pathname==='/api/auth/login'){const b=await readBody(req),u=db.prepare('SELECT * FROM users WHERE email=?').get(String(b.email||'').toLowerCase());if(!u||!checkPassword(u,String(b.password||'')))return fail(res,401,'Email or password is incorrect');const token=crypto.randomBytes(32).toString('base64url'),expires=new Date(Date.now()+12*60*60*1000).toISOString();db.prepare('INSERT INTO sessions(token_hash,user_id,expires_at) VALUES(?,?,?)').run(hash(token),u.id,expires);send(res,200,{user:{id:u.id,name:u.name,role:u.role}}, {'set-cookie':`hc_session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=43200`});return}
  if(req.method==='POST'&&url.pathname==='/api/auth/logout'){const u=auth(req);const token=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('hc_session='))?.slice(11);if(token)db.prepare('DELETE FROM sessions WHERE token_hash=?').run(hash(token));send(res,200,{ok:true},{'set-cookie':'hc_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0'});return}
  const user=auth(req);if(url.pathname==='/api/session'&&req.method==='GET'){if(!user)return send(res,200,{user:null});return send(res,200,{user:{id:user.id,name:user.name,role:user.role}})}
  if(!user)return fail(res,401,'Sign in to continue');
  if(url.pathname==='/api/health'){send(res,200,{status:'ok',database:'connected'});return}
  if(url.pathname==='/api/patient'&&req.method==='GET'&&requireRole(user,'patient','doctor')){const p=patientFor(user);if(user.role==='doctor'){const c=db.prepare('SELECT enabled FROM consents WHERE patient_id=? AND grantee=? AND scope=?').get(p.id,'doctor','health_record');if(!c?.enabled)return fail(res,403,'Patient has not granted record access')}audit(p,user,'view','patient_summary');send(res,200,{patient:{id:p.id,name:p.full_name,healthId:p.health_id,bloodGroup:p.blood_group,pregnancyWeek:p.pregnancy_week,dueDate:p.due_date,language:p.language,region:p.region}});return}
  if(url.pathname==='/api/pain'&&req.method==='GET'&&requireRole(user,'patient','doctor')){const p=patientFor(user);if(user.role==='doctor'&&!db.prepare('SELECT enabled FROM consents WHERE patient_id=? AND grantee=? AND scope=?').get(p.id,'doctor','health_record')?.enabled)return fail(res,403,'Patient consent required');audit(p,user,'view','pain_checkins');send(res,200,{checkins:db.prepare('SELECT id,score,symptoms,note,created_at AS createdAt FROM pain_checkins WHERE patient_id=? ORDER BY id').all(p.id)});return}
  if(url.pathname==='/api/pain'&&req.method==='POST'&&requireRole(user,'patient')){const p=patientFor(user),b=await readBody(req);if(!Number.isInteger(b.score)||b.score<0||b.score>10)return fail(res,400,'Pain score must be from 0 to 10');const symptoms=Array.isArray(b.symptoms)?b.symptoms.map(x=>String(x).slice(0,60)).slice(0,12):[];const r=db.prepare('INSERT INTO pain_checkins(patient_id,score,symptoms,note,created_at) VALUES(?,?,?,?,?)').run(p.id,b.score,JSON.stringify(symptoms),String(b.note||'').slice(0,1000),now());audit(p,user,'create','pain_checkin');send(res,201,{id:Number(r.lastInsertRowid),score:b.score,createdAt:now()});return}
  if(url.pathname==='/api/consents'&&req.method==='GET'&&requireRole(user,'patient')){const p=patientFor(user);send(res,200,{consents:db.prepare('SELECT grantee,scope,enabled,updated_at AS updatedAt FROM consents WHERE patient_id=?').all(p.id)});return}
  if(url.pathname==='/api/consents'&&req.method==='PUT'&&requireRole(user,'patient')){const p=patientFor(user),b=await readBody(req);if(!['husband','mother','father','doctor','family','contacts'].includes(b.grantee)||!['emergency_alert','emergency_location','full_record','health_record'].includes(b.scope)||typeof b.enabled!=='boolean')return fail(res,400,'Invalid consent choice');db.prepare(`INSERT INTO consents(patient_id,grantee,scope,enabled,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(patient_id,grantee,scope) DO UPDATE SET enabled=excluded.enabled,updated_at=excluded.updated_at`).run(p.id,b.grantee,b.scope,+b.enabled,now());audit(p,user,'update_consent',`${b.grantee}:${b.scope}`);send(res,200,{ok:true});return}
  if(url.pathname==='/api/emergency/alert'&&req.method==='POST'&&requireRole(user,'patient')){const p=patientFor(user),b=await readBody(req),sym=Array.isArray(b.symptoms)?b.symptoms.slice(0,12):[];const cons=db.prepare('SELECT grantee,scope,enabled FROM consents WHERE patient_id=? AND enabled=1').all(p.id),alertCons=cons.filter(x=>x.scope==='emergency_alert').map(x=>x.grantee),shareLocation=!!b.shareLocation&&cons.some(x=>x.scope==='emergency_location');if(!alertCons.length)return fail(res,409,'No emergency contacts are currently authorized');const id=crypto.randomUUID(),details={score:Number(b.score)||0,symptoms:sym,pattern:Array.isArray(b.pattern)?b.pattern.map(x=>Number(x)).filter(x=>Number.isInteger(x)&&x>=0&&x<=10).slice(-60):[],recipients:alertCons};db.prepare('INSERT INTO alerts(id,patient_id,kind,status,details,location_shared,created_at) VALUES(?,?,?,?,?,?,?)').run(id,p.id,'patient_requested','sent',JSON.stringify(details),+shareLocation,now());audit(p,user,'create','emergency_alert');send(res,201,{id,status:'sent',recipients:alertCons,locationShared:shareLocation,simulated:true});return}
  if(url.pathname==='/api/emergency/safe'&&req.method==='POST'&&requireRole(user,'patient')){const p=patientFor(user),latest=db.prepare("SELECT id FROM alerts WHERE patient_id=? AND status='sent' ORDER BY created_at DESC LIMIT 1").get(p.id);if(latest)db.prepare("UPDATE alerts SET status='safe',safe_at=? WHERE id=?").run(now(),latest.id);audit(p,user,'update','emergency_status');send(res,200,{ok:true,status:'safe'});return}
  if(url.pathname==='/api/reports'&&req.method==='GET'&&requireRole(user,'patient','doctor')){const p=patientFor(user);if(user.role==='doctor'&&!db.prepare('SELECT enabled FROM consents WHERE patient_id=? AND grantee=? AND scope=?').get(p.id,'doctor','health_record')?.enabled)return fail(res,403,'Patient consent required');audit(p,user,'view','reports');send(res,200,{reports:db.prepare('SELECT id,order_id AS orderId,file_name AS fileName,summary,created_at AS createdAt FROM reports WHERE patient_id=? ORDER BY created_at DESC').all(p.id)});return}if(url.pathname==='/api/visits'&&req.method==='GET'&&requireRole(user,'patient','doctor')){const p=patientFor(user);audit(p,user,'view','visits');send(res,200,{visits:db.prepare('SELECT id,clinician,visit_type AS type,visit_at AS visitAt,note,follow_up AS followUp FROM visits WHERE patient_id=? ORDER BY visit_at DESC').all(p.id)});return}
  if(url.pathname==='/api/visits'&&req.method==='POST'&&requireRole(user,'doctor')){const p=patientFor(user);if(!db.prepare('SELECT enabled FROM consents WHERE patient_id=? AND grantee=? AND scope=?').get(p.id,'doctor','health_record')?.enabled)return fail(res,403,'Patient consent required');const b=await readBody(req),id=crypto.randomUUID();db.prepare('INSERT INTO visits(id,patient_id,clinician,visit_type,visit_at,note,follow_up,created_at) VALUES(?,?,?,?,?,?,?,?)').run(id,p.id,user.name,String(b.type||'Consultation').slice(0,100),String(b.visitAt||now()).slice(0,40),String(b.note||'').slice(0,4000),String(b.followUp||'').slice(0,2000),now());audit(p,user,'create','visit');send(res,201,{id});return}
  if(url.pathname==='/api/medicines'&&req.method==='GET'&&requireRole(user,'patient','doctor')){const p=patientFor(user);audit(p,user,'view','medicines');send(res,200,{medicines:db.prepare('SELECT id,name,directions,reminder_time AS reminderTime FROM medicines WHERE patient_id=? AND active=1').all(p.id)});return}
  if(url.pathname.startsWith('/api/medicines/')&&url.pathname.endsWith('/taken')&&req.method==='POST'&&requireRole(user,'patient')){const id=url.pathname.split('/')[3],p=patientFor(user);if(!db.prepare('SELECT 1 FROM medicines WHERE id=? AND patient_id=?').get(id,p.id))return fail(res,404,'Medicine not found');db.prepare('INSERT INTO medicine_logs(medicine_id,patient_id,taken_at) VALUES(?,?,?)').run(id,p.id,now());audit(p,user,'create','medicine_log');send(res,201,{ok:true});return}
  if(url.pathname==='/api/lab/order'&&req.method==='GET'&&requireRole(user,'lab')){const o=db.prepare('SELECT id,test_name AS testName,status,ordered_by AS orderedBy,created_at AS createdAt FROM test_orders WHERE lab_user_id=? ORDER BY created_at DESC LIMIT 1').get(user.id);if(!o)return fail(res,404,'No assigned test order');audit(db.prepare('SELECT * FROM patients WHERE id=(SELECT patient_id FROM test_orders WHERE id=?)').get(o.id),user,'view','assigned_test_order');send(res,200,{order:o});return}
  if(url.pathname==='/api/lab/report'&&req.method==='POST'&&requireRole(user,'lab')){const b=await readBody(req),o=db.prepare('SELECT * FROM test_orders WHERE id=? AND lab_user_id=?').get(String(b.orderId||''),user.id);if(!o)return fail(res,403,'This test order is not assigned to your lab');let storedName='';if(b.base64){const raw=Buffer.from(String(b.base64).replace(/^data:[^;]+;base64,/,''),'base64');if(raw.length>6*1024*1024)return fail(res,413,'Report exceeds 6 MB');storedName=`${crypto.randomUUID()}${path.extname(String(b.fileName||'').replace(/[^\w. -]/g,'_')).slice(0,12)}`;fs.writeFileSync(path.join(DATA,'uploads',storedName),raw)}const id=crypto.randomUUID();db.prepare('INSERT INTO reports(id,order_id,patient_id,file_name,stored_name,summary,uploaded_by,created_at) VALUES(?,?,?,?,?,?,?,?)').run(id,o.id,o.patient_id,String(b.fileName||'result-entry').slice(0,180),storedName,String(b.summary||'').slice(0,2000),user.id,now());db.prepare("UPDATE test_orders SET status='report_uploaded' WHERE id=?").run(o.id);audit(db.prepare('SELECT * FROM patients WHERE id=?').get(o.patient_id),user,'upload','assigned_test_report');send(res,201,{id,status:'uploaded'});return}
  if(url.pathname==='/api/access-history'&&req.method==='GET'&&requireRole(user,'patient')){const p=patientFor(user);send(res,200,{entries:db.prepare('SELECT a.action,a.resource,a.created_at AS createdAt,u.name AS actor,u.role AS role FROM access_log a JOIN users u ON u.id=a.actor_id WHERE a.patient_id=? ORDER BY a.id DESC LIMIT 100').all(p.id)});return}
  return fail(res,404,'API route not found');
}
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,'http://localhost');try{if(url.pathname.startsWith('/api/'))return await api(req,res,url);if(req.method!=='GET'&&req.method!=='HEAD'){res.writeHead(405);return res.end('Method not allowed')}let p=decodeURIComponent(url.pathname==='/ '?'/':url.pathname);if(p==='/'||p==='/')p='/index.html';const f=path.resolve(ROOT,'.'+p);if(!f.startsWith(ROOT+path.sep))return fail(res,404,'Not found');fs.readFile(f,(e,data)=>{if(e){res.writeHead(404);res.end('Not found');return}res.writeHead(200,{'content-type':mime[path.extname(f)]||'application/octet-stream','x-content-type-options':'nosniff','referrer-policy':'same-origin'});res.end(data)})}catch(e){if(!res.headersSent)fail(res,e.status||500,e.status?e.message:'Unexpected server error');else res.destroy();if(!e.status)console.error(e)}});
const port=Number(process.env.PORT||3000);server.listen(port,'127.0.0.1',()=>console.log(`HERCARE platform running at http://127.0.0.1:${port}`));
